# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogitGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 521, 41))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 130, 401, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxQuality = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxQuality.setObjectName("checkBoxQuality")
        self.verticalLayout.addWidget(self.checkBoxQuality)
        self.checkBoxSignif = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxSignif.setObjectName("checkBoxSignif")
        self.verticalLayout.addWidget(self.checkBoxSignif)
        self.checkBoxTable = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxTable.setObjectName("checkBoxTable")
        self.verticalLayout.addWidget(self.checkBoxTable)
        self.checkBoxResid = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxResid.setObjectName("checkBoxResid")
        self.verticalLayout.addWidget(self.checkBoxResid)
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(330, 420, 113, 32))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButtonDone = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDone.setGeometry(QtCore.QRect(460, 420, 113, 32))
        self.pushButtonDone.setObjectName("pushButtonDone")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Выберите, какие таблицы и графики Вы бы хотели увидеть:</span></p></body></html>"))
        self.checkBoxQuality.setText(_translate("MainWindow", "Таблица с критериями качества построенной модели"))
        self.checkBoxSignif.setText(_translate("MainWindow", "Таблица с критериями значимости \n"
" для каждой независимой переменной"))
        self.checkBoxTable.setText(_translate("MainWindow", "Классификационная таблица"))
        self.checkBoxResid.setText(_translate("MainWindow", "Таблица с анализом отстатков"))
        self.pushButtonBack.setText(_translate("MainWindow", "Назад"))
        self.pushButtonDone.setText(_translate("MainWindow", "Завершить"))
