# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class StartingWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 70, 371, 41))
        self.label.setObjectName("label")
        self.pushButtonDone = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDone.setGeometry(QtCore.QRect(450, 390, 121, 32))
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.pushButtonStat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStat.setGeometry(QtCore.QRect(90, 180, 401, 32))
        self.pushButtonStat.setObjectName("pushButtonStat")
        self.pushButtonBioeq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBioeq.setGeometry(QtCore.QRect(90, 224, 401, 32))
        self.pushButtonBioeq.setObjectName("pushButtonBioeq")
        self.pushButtonPred = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPred.setGeometry(QtCore.QRect(90, 268, 401, 32))
        self.pushButtonPred.setObjectName("pushButtonPred")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Для начала работы с модулем выберите файл:"))
        self.pushButtonDone.setText(_translate("MainWindow", "Завершить"))
        self.pushButtonStat.setText(_translate("MainWindow", "Статический анализ"))
        self.pushButtonBioeq.setText(_translate("MainWindow", "Биоэквивалентность"))
        self.pushButtonPred.setText(_translate("MainWindow", "Предсказательные модели"))
