# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DesignWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 50, 421, 31))
        self.label.setObjectName("label")
        self.radioButton_parall = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_parall.setGeometry(QtCore.QRect(100, 130, 171, 20))
        self.radioButton_parall.setObjectName("radioButton_parall")
        self.radioButton_cross = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_cross.setGeometry(QtCore.QRect(100, 180, 251, 20))
        self.radioButton_cross.setObjectName("radioButton_cross")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(330, 420, 113, 32))
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(460, 420, 113, 32))
        self.pushButtonNext.setObjectName("pushButtonNext")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Укажите, с какой выборкой проводится работа:</span></p></body></html>"))
        self.radioButton_parall.setText(_translate("MainWindow", "Параллельный дизайн"))
        self.radioButton_cross.setText(_translate("MainWindow", "Перекрестный дизайн"))
        self.pushButtonBack.setText(_translate("MainWindow", "Назад"))
        self.pushButtonNext.setText(_translate("MainWindow", "Вперед"))
