# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TablesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TablesWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 60, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 130, 331, 16))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 180, 495, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxFeatures = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxFeatures.setObjectName("checkBoxFeatures")
        self.verticalLayout.addWidget(self.checkBoxFeatures)
        self.checkBoxDistrub = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxDistrub.setObjectName("checkBoxDistrub")
        self.verticalLayout.addWidget(self.checkBoxDistrub)
        self.checkBoxPowers = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxPowers.setObjectName("checkBoxPowers")
        self.verticalLayout.addWidget(self.checkBoxPowers)
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(460, 420, 113, 32))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(330, 420, 113, 32))
        self.pushButtonBack.setObjectName("pushButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Выбор графиков"))
        self.label_2.setText(_translate("MainWindow", "Выберите таблицы, Вы которые хотели бы увидеть:"))
        self.checkBoxFeatures.setText(_translate("MainWindow", "Индивидуальные фармокинетические свойства препарата"))
        self.checkBoxDistrub.setText(_translate("MainWindow", "Распределение ключевых параметров по группам"))
        self.checkBoxPowers.setText(_translate("MainWindow", "Статистические мощности по ключевым параметрам"))
        self.pushButtonNext.setText(_translate("MainWindow", "Вперед"))
        self.pushButtonBack.setText(_translate("MainWindow", "Назад"))
